name: Build
on:
  - push
  - pull_request
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: pnpm/action-setup@v2
          with:
            version: 6.0.2
        - uses: actions/checkout@v2
        - name: Install Alkstore modules
          run: pnpm install
        - name: Run Alkstore build
          run: pnpm build
        - name: Run Example build
          run: cd example && pnpm install && pnpm build